services:
  irrigation:
    build: ./server
    image: irrigation-server
    container_name: irrigation-server
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    stdin_open: true
    tty: true
  
  irrigation-ui:
    build: ./frontend/irrigationUI
    image: irrigation-ui
    container_name: irrigation-ui
    ports:
      - "8000:8000"
