services:
  irrigation:
    build: ./
    image: irrigation-server
    container_name: irrigation-server
    networks:
      - irrigation-network
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    stdin_open: true
    tty: true



networks:
  irrigation-network:
    external: true